services:
  pythonapplikation:
    build: ./python/
    command: sh -c "sleep 20s ; python3 ./commands.py"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    build: ./mysql/
    restart: always

    environment:
      MYSQL_DATABASE: abschlussarbeit
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_PASSWORD:
    ports:
      - "3300:3306"
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-e", "SHOW DATABASES LIKE 'abschlussarbeit';"]
      interval: 10s
      timeout: 15s
      retries: 10
