services:
  devcontainer: 
    image: mcr.microsoft.com/vscode/devcontainers/python:3
    container_name: abschlussprojekt
    command: sleep infinity
    volumes:
      - .:/workspace
    networks:
      - app-network
  
  pythonapplikation:
    build: ./python/
    command: sh -c "sleep 20s ; python3 ./commands.ipynb"
    networks:
      - app-network

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: abschlussarbeit
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3366:3306"
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-e", "SHOW DATABASES LIKE 'abschlussarbeit';"]
      interval: 10s
      timeout: 15s
      retries: 10
    networks:
      - app-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge