services:
  devconatiner: 
    image: mcr.microsoft.com/vscode/devcontainers/python:3
    container_name: abschlussprojekt
    volumes:
      - .:/app
    command: sleep infinity
    nework_mode: service:mysql
  
  pythonapplikation:
    build: ./python/
    command: sh -c "sleep 20s ; python3 ./commands.py"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    build: ./mysql/
    restart: always

    environment:
      MYSQL_DATABASE: abschlussarbeit
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-e", "SHOW DATABASES LIKE 'abschlussarbeit';"]
      interval: 10s
      timeout: 15s
      retries: 10
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy

